apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: scale-deployment-pubsub
  namespace: test-model
spec:
  minReplicas: 1
  maxReplicas: 80
  metrics:
  - external:
      metricName: pubsub.googleapis.com|subscription|num_undelivered_messages
      metricSelector:
        matchLabels:
          resource.labels.project_id: poc-innovation-iot
          resource.labels.subscription_id: chulaxktb-image-validation-sub
      targetAverageValue: "10"
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: model-deployment
