  apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
    name: model-ingress
    namespace: test-model
  spec:
    rules:
      - host:
        http:
          paths:
            - backend:
                serviceName: model-service
                servicePort: 80
              path: /
