apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
  labels:
    app: model
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model
        image: gcr.io/cloud-devrel-public-resources/gcloud-container-1.14.0:latest
        volumeMounts: 
        - name: model-path
          mountPath: /tmp/mounted_model/0001
        ports:
        - containerPort: 8501
      volumes:
      - name: model-path
        hostPath:
          path: /tmp/mounted_model/0001
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  type: ClusterIP
  selector:
    app: model
  ports:
    - name: http
      protocol: TCP
      port: 8501
      targetPort: 8501