apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: model-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  backend:
    serviceName: model-service
    servicePort: 8501
